name: Local Test Workflow

on:
  # For testing locally with Act
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance tqdm

    - name: Run signal generator script
      id: run_script
      run: |
        cd $GITHUB_WORKSPACE
        python scripts/high_current.py > signal_output.txt
      continue-on-error: true

    # Set current date for all steps
    - name: Set current date
      id: set_date
      run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # Process the signal with enhanced reporting
    - name: Process signals with enhanced report
      id: enhance_report
      run: |
        # Find the latest signal JSON file
        LATEST_JSON=$(find results/live_signals -type f -name "daily_signal_*.json" | sort -r | head -n 1)
        
        if [ -n "$LATEST_JSON" ]; then
          echo "Latest JSON file: $LATEST_JSON"
          echo "Generating enhanced report..."
          
          # Generate the enhanced report with signal tracking
          python enhanced_report.py "$LATEST_JSON" report.txt no
          
          if [ -f report.txt ] && [ -s report.txt ]; then
            echo "report_exists=true" >> $GITHUB_OUTPUT
            echo "report_not_empty=true" >> $GITHUB_OUTPUT
            echo "Enhanced report generated successfully."
            
            # Track signals automatically (only track overall signal)
            python auto_tracker.py --file "$LATEST_JSON"
            
            # Display report summary
            echo "Report summary:"
            head -n 10 report.txt
            echo "..."
          else
            echo "report_exists=false" >> $GITHUB_OUTPUT
            echo "report_not_empty=false" >> $GITHUB_OUTPUT
            echo "Failed to generate enhanced report."
          fi
        else
          echo "No JSON file found."
          echo "report_exists=false" >> $GITHUB_OUTPUT
          echo "report_not_empty=false" >> $GITHUB_OUTPUT
        fi

    # Show tracked trades
    - name: Display tracked trades
      if: steps.enhance_report.outputs.report_exists == 'true' && steps.enhance_report.outputs.report_not_empty == 'true'
      run: |
        echo "Tracked trades:"
        if [ -f "tracking/trades.csv" ]; then
          cat tracking/trades.csv
        else
          echo "No trades.csv file found"
        fi
