name: Daily Report

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance tqdm logging

    - name: Run script and capture output
      id: run_script # Added id
      run: |
        cd $GITHUB_WORKSPACE
        python scripts/high_current.py > report.txt
      continue-on-error: true

    - name: Store report output
      id: store_report_output # Added id
      run: |
        if [ -f report.txt ]; then
          echo "REPORT_OUTPUT=$(cat report.txt)" >> $GITHUB_ENV
        else
          echo "report.txt not found, skipping storing output."
        fi
      # Removed if: success() to allow this to run even if script fails,
      # but it will only store output if report.txt exists.

    - name: Check report status
      id: check_report_status # Renamed and added id
      run: |
        if [ -f report.txt ]; then
          echo "::set-output name=report_exists::true"
          if [ -s report.txt ]; then
            echo "::set-output name=report_not_empty::true"
            echo "Report file exists and is not empty."
          else
            echo "::set-output name=report_not_empty::false"
            echo "Report file exists but is empty."
            # Optionally, fail the workflow if the report is empty and this is considered a failure
            # exit 1
          fi
        else
          echo "::set-output name=report_exists::false"
          echo "::set-output name=report_not_empty::false"
          echo "Report file does not exist."
          # Optionally, fail the workflow if the report file is missing and this is considered a failure
          # exit 1
        fi
      # This step should run regardless of script success to check the file.
      # The condition if: success() was here, removing it.
      # We'll control email sending based on its outputs.

    - name: Set current date
      id: set_date
      run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Send email report
      if: steps.check_report_status.outputs.report_exists == 'true' && steps.check_report_status.outputs.report_not_empty == 'true' && always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Daily Trading Signal Report - {{ env.TODAY_DATE }}
        body: file://report.txt
        to: katar.fhm@gmail.com
        from: Rojhak Azadi <rojhak.azadi@gmail.com>
        content_type: text/plain # Explicitly setting to plain text as html_body is false
        html_body: false
        secure: true
